### ISSUE TITLE
Hot Chocolate v13

### ISSUE THREAD

**Issue by glen-84** [appany/AppAny.HotChocolate.FluentValidation#103]
Would it be possible to release a preview version compatible with HC 13?

At the moment I'm getting:

> Unhandled exception. System.MissingMethodException: Method not found: 'HotChocolate.NameString HotChocolate.Types.IHasName.get_Name()'.
   at AppAny.HotChocolate.FluentValidation.ValidationInterceptors.OnAfterSchemaCreate(IDescriptorContext descriptorContext, ISchema schema)
   at HotChocolate.Configuration.DelegateSchemaInterceptor.OnAfterCreate(IDescriptorContext context, ISchema schema)
   at HotChocolate.Configuration.AggregateSchemaInterceptor.OnAfterCreate(IDescriptorContext context, ISchema schema)
   at HotChocolate.SchemaBuilder.Setup.CompleteSchema(SchemaBuilder builder, IDescriptorContext context, LazySchema lazySchema, TypeRegistry typeRegistry)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Warmup.ExecutorWarmupService.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in /home/glen/development-environment/projects/api-next/src/Application/Program.cs:line 70
   at Program.<Main>(String[] args)

**Comment by glen-84** [comment]
All tests are passing here: https://github.com/glen-84/AppAny.HotChocolate.FluentValidation/commit/b753aa039a8e155eee75477bd804f29e64c184d9

**Comment by glen-84** [comment]
@sergeyshaykhullin Can I send a PR to a new branch, or do I need to publish this elsewhere?

**Comment by sergeyshaykhullin** [comment]
@glen-84 https://www.nuget.org/packages/AppAny.HotChocolate.FluentValidation/0.10.0
